/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as WebsiteAuditRouteImport } from './routes/website-audit'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as OutreachGeneratorRouteImport } from './routes/outreach-generator'
import { Route as OpportunityScoringRouteImport } from './routes/opportunity-scoring'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as MarketResearchRouteImport } from './routes/market-research'
import { Route as LeadGenerationRouteImport } from './routes/lead-generation'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as CompetitorsRouteImport } from './routes/competitors'
import { Route as IndexRouteImport } from './routes/index'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteAuditRoute = WebsiteAuditRouteImport.update({
  id: '/website-audit',
  path: '/website-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachGeneratorRoute = OutreachGeneratorRouteImport.update({
  id: '/outreach-generator',
  path: '/outreach-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunityScoringRoute = OpportunityScoringRouteImport.update({
  id: '/opportunity-scoring',
  path: '/opportunity-scoring',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketResearchRoute = MarketResearchRouteImport.update({
  id: '/market-research',
  path: '/market-research',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadGenerationRoute = LeadGenerationRouteImport.update({
  id: '/lead-generation',
  path: '/lead-generation',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitorsRoute = CompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/competitors': typeof CompetitorsRoute
  '/intelligence': typeof IntelligenceRoute
  '/lead-generation': typeof LeadGenerationRoute
  '/market-research': typeof MarketResearchRoute
  '/monitoring': typeof MonitoringRoute
  '/opportunity-scoring': typeof OpportunityScoringRoute
  '/outreach-generator': typeof OutreachGeneratorRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/website-audit': typeof WebsiteAuditRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/competitors': typeof CompetitorsRoute
  '/intelligence': typeof IntelligenceRoute
  '/lead-generation': typeof LeadGenerationRoute
  '/market-research': typeof MarketResearchRoute
  '/monitoring': typeof MonitoringRoute
  '/opportunity-scoring': typeof OpportunityScoringRoute
  '/outreach-generator': typeof OutreachGeneratorRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/website-audit': typeof WebsiteAuditRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/competitors': typeof CompetitorsRoute
  '/intelligence': typeof IntelligenceRoute
  '/lead-generation': typeof LeadGenerationRoute
  '/market-research': typeof MarketResearchRoute
  '/monitoring': typeof MonitoringRoute
  '/opportunity-scoring': typeof OpportunityScoringRoute
  '/outreach-generator': typeof OutreachGeneratorRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/website-audit': typeof WebsiteAuditRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/competitors'
    | '/intelligence'
    | '/lead-generation'
    | '/market-research'
    | '/monitoring'
    | '/opportunity-scoring'
    | '/outreach-generator'
    | '/reports'
    | '/settings'
    | '/website-audit'
    | '/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/competitors'
    | '/intelligence'
    | '/lead-generation'
    | '/market-research'
    | '/monitoring'
    | '/opportunity-scoring'
    | '/outreach-generator'
    | '/reports'
    | '/settings'
    | '/website-audit'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/competitors'
    | '/intelligence'
    | '/lead-generation'
    | '/market-research'
    | '/monitoring'
    | '/opportunity-scoring'
    | '/outreach-generator'
    | '/reports'
    | '/settings'
    | '/website-audit'
    | '/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompetitorsRoute: typeof CompetitorsRoute
  IntelligenceRoute: typeof IntelligenceRoute
  LeadGenerationRoute: typeof LeadGenerationRoute
  MarketResearchRoute: typeof MarketResearchRoute
  MonitoringRoute: typeof MonitoringRoute
  OpportunityScoringRoute: typeof OpportunityScoringRoute
  OutreachGeneratorRoute: typeof OutreachGeneratorRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  WebsiteAuditRoute: typeof WebsiteAuditRoute
  WorkspaceRoute: typeof WorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-audit': {
      id: '/website-audit'
      path: '/website-audit'
      fullPath: '/website-audit'
      preLoaderRoute: typeof WebsiteAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach-generator': {
      id: '/outreach-generator'
      path: '/outreach-generator'
      fullPath: '/outreach-generator'
      preLoaderRoute: typeof OutreachGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunity-scoring': {
      id: '/opportunity-scoring'
      path: '/opportunity-scoring'
      fullPath: '/opportunity-scoring'
      preLoaderRoute: typeof OpportunityScoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-research': {
      id: '/market-research'
      path: '/market-research'
      fullPath: '/market-research'
      preLoaderRoute: typeof MarketResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lead-generation': {
      id: '/lead-generation'
      path: '/lead-generation'
      fullPath: '/lead-generation'
      preLoaderRoute: typeof LeadGenerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitors': {
      id: '/competitors'
      path: '/competitors'
      fullPath: '/competitors'
      preLoaderRoute: typeof CompetitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompetitorsRoute: CompetitorsRoute,
  IntelligenceRoute: IntelligenceRoute,
  LeadGenerationRoute: LeadGenerationRoute,
  MarketResearchRoute: MarketResearchRoute,
  MonitoringRoute: MonitoringRoute,
  OpportunityScoringRoute: OpportunityScoringRoute,
  OutreachGeneratorRoute: OutreachGeneratorRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  WebsiteAuditRoute: WebsiteAuditRoute,
  WorkspaceRoute: WorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
