"""graph_v3_full_schema

Revision ID: 0001
Revises: 
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=400), nullable=False),
    sa.Column('name_key', sa.String(length=400), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('merged_into', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name_key', name='uq_entity_ws_namekey')
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index('ix_entities_merged_into', ['merged_into'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_name_key'), ['name_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('entity_merge_candidates',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('a_id', sa.String(length=32), nullable=False),
    sa.Column('b_id', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity_merge_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_merge_candidates_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('entity_merge_log',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('loser_id', sa.String(length=32), nullable=False),
    sa.Column('winner_id', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity_merge_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_merge_log_loser_id'), ['loser_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_merge_log_winner_id'), ['winner_id'], unique=False)

    op.create_table('events',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('seq')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_run_id'), ['run_id'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('canonical_url', sa.String(length=1000), nullable=False),
    sa.Column('domain', sa.String(length=300), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('published_date', sa.String(length=40), nullable=True),
    sa.Column('retrieved_at', sa.String(length=40), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_canonical_url'), ['canonical_url'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_retrieved_at'), ['retrieved_at'], unique=False)

    op.create_table('insights',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('claim_ids', sa.JSON(), nullable=False),
    sa.Column('trust', sa.JSON(), nullable=False),
    sa.Column('authored_by', sa.String(length=60), nullable=False),
    sa.Column('debate_status', sa.String(length=20), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insights_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_insights_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_insights_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_insights_ws_org', ['workspace_id', 'organization_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('heartbeat_at', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('monitoring_config',
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('cadence', sa.String(length=20), nullable=False),
    sa.Column('budget', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('organization_id')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claims',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('subject_entity_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('value', sa.String(length=400), nullable=True),
    sa.Column('predicate', sa.String(length=80), nullable=True),
    sa.Column('topic', sa.String(length=60), nullable=False),
    sa.Column('as_of', sa.String(length=40), nullable=True),
    sa.Column('identity_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('trust', sa.JSON(), nullable=False),
    sa.Column('superseded_by', sa.String(length=32), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_hash', name='uq_claim_identity')
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_kind'), ['kind'], unique=False)
        batch_op.create_index('ix_claims_run', ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_subject_entity_id'), ['subject_entity_id'], unique=False)
        batch_op.create_index('ix_claims_subject_predicate', ['subject_entity_id', 'predicate'], unique=False)
        batch_op.create_index('ix_claims_subject_topic', ['subject_entity_id', 'topic'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_topic'), ['topic'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_claims_ws_created', ['workspace_id', 'created_at'], unique=False)

    op.create_table('entity_aliases',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('alias_key', sa.String(length=400), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'alias_key', name='uq_alias')
    )
    with op.batch_alter_table('entity_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_aliases_alias_key'), ['alias_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_aliases_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_aliases_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('evidence_chunks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('embed_model', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_id', 'seq', name='uq_chunk_seq')
    )
    with op.batch_alter_table('evidence_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_chunks_evidence_id'), ['evidence_id'], unique=False)

    op.create_table('extraction_cache',
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('subject_entity_id', sa.String(length=32), nullable=False),
    sa.Column('topic', sa.String(length=60), nullable=False),
    sa.Column('extraction_version', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('evidence_id', 'subject_entity_id', 'topic', 'extraction_version')
    )
    op.create_table('organizations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('root_entity_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('claim_evidence',
    sa.Column('claim_id', sa.String(length=32), nullable=False),
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('claim_id', 'evidence_id')
    )
    with op.batch_alter_table('claim_evidence', schema=None) as batch_op:
        batch_op.create_index('ix_claim_evidence_evidence', ['evidence_id'], unique=False)

    op.create_table('edges',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('source_entity_id', sa.String(length=32), nullable=False),
    sa.Column('relation', sa.String(length=60), nullable=False),
    sa.Column('target_entity_id', sa.String(length=32), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('trust', sa.JSON(), nullable=False),
    sa.Column('as_of', sa.String(length=40), nullable=True),
    sa.Column('claim_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'source_entity_id', 'relation', 'target_entity_id', name='uq_edge_triple')
    )
    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edges_relation'), ['relation'], unique=False)
        batch_op.create_index(batch_op.f('ix_edges_source_entity_id'), ['source_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edges_target_entity_id'), ['target_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edges_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('insight_claim',
    sa.Column('insight_id', sa.String(length=32), nullable=False),
    sa.Column('claim_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['insight_id'], ['insights.id'], ),
    sa.PrimaryKeyConstraint('insight_id', 'claim_id')
    )
    with op.batch_alter_table('insight_claim', schema=None) as batch_op:
        batch_op.create_index('ix_insight_claim_claim', ['claim_id'], unique=False)

    op.create_table('runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=True),
    sa.Column('request', sa.JSON(), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('costs', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('edge_evidence',
    sa.Column('edge_id', sa.String(length=32), nullable=False),
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['edge_id'], ['edges.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('edge_id', 'evidence_id')
    )
    with op.batch_alter_table('edge_evidence', schema=None) as batch_op:
        batch_op.create_index('ix_edge_evidence_evidence', ['evidence_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edge_evidence', schema=None) as batch_op:
        batch_op.drop_index('ix_edge_evidence_evidence')

    op.drop_table('edge_evidence')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_runs_organization_id'))

    op.drop_table('runs')
    with op.batch_alter_table('insight_claim', schema=None) as batch_op:
        batch_op.drop_index('ix_insight_claim_claim')

    op.drop_table('insight_claim')
    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edges_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_edges_target_entity_id'))
        batch_op.drop_index(batch_op.f('ix_edges_source_entity_id'))
        batch_op.drop_index(batch_op.f('ix_edges_relation'))

    op.drop_table('edges')
    with op.batch_alter_table('claim_evidence', schema=None) as batch_op:
        batch_op.drop_index('ix_claim_evidence_evidence')

    op.drop_table('claim_evidence')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_organizations_name'))

    op.drop_table('organizations')
    op.drop_table('extraction_cache')
    with op.batch_alter_table('evidence_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_chunks_evidence_id'))

    op.drop_table('evidence_chunks')
    with op.batch_alter_table('entity_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_aliases_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_entity_aliases_entity_id'))
        batch_op.drop_index(batch_op.f('ix_entity_aliases_alias_key'))

    op.drop_table('entity_aliases')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index('ix_claims_ws_created')
        batch_op.drop_index(batch_op.f('ix_claims_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_claims_topic'))
        batch_op.drop_index('ix_claims_subject_topic')
        batch_op.drop_index('ix_claims_subject_predicate')
        batch_op.drop_index(batch_op.f('ix_claims_subject_entity_id'))
        batch_op.drop_index(batch_op.f('ix_claims_status'))
        batch_op.drop_index('ix_claims_run')
        batch_op.drop_index(batch_op.f('ix_claims_kind'))

    op.drop_table('claims')
    op.drop_table('workspaces')
    op.drop_table('monitoring_config')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))

    op.drop_table('jobs')
    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.drop_index('ix_insights_ws_org')
        batch_op.drop_index(batch_op.f('ix_insights_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_insights_organization_id'))
        batch_op.drop_index(batch_op.f('ix_insights_kind'))

    op.drop_table('insights')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_retrieved_at'))
        batch_op.drop_index(batch_op.f('ix_evidence_domain'))
        batch_op.drop_index(batch_op.f('ix_evidence_canonical_url'))

    op.drop_table('evidence')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_run_id'))

    op.drop_table('events')
    with op.batch_alter_table('entity_merge_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_merge_log_winner_id'))
        batch_op.drop_index(batch_op.f('ix_entity_merge_log_loser_id'))

    op.drop_table('entity_merge_log')
    with op.batch_alter_table('entity_merge_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_merge_candidates_workspace_id'))

    op.drop_table('entity_merge_candidates')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entities_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_entities_name_key'))
        batch_op.drop_index(batch_op.f('ix_entities_name'))
        batch_op.drop_index('ix_entities_merged_into')

    op.drop_table('entities')
    # ### end Alembic commands ###
