/**
 * Report builder — assembles shareable executive reports from data the platform
 * already holds (dashboard findings, recommendations, history). Pure functions,
 * no network. Powers the Reports page's real actions (copy / markdown / HTML /
 * print). Nothing is fabricated: everything comes from the graph payload.
 */
import type { DashboardView, GraphInsight } from "@/services/intelligence";

export type ReportKind = "executive" | "board" | "research" | "opportunity";

export const REPORT_META: Record<
  ReportKind,
  { name: string; audience: string; description: string }
> = {
  executive: {
    name: "Executive Summary",
    audience: "Leadership",
    description:
      "The headline picture: verified findings, top recommendations, and open questions.",
  },
  board: {
    name: "Board Report",
    audience: "Board & investors",
    description: "A concise, high-level briefing suitable for a board packet.",
  },
  research: {
    name: "Research Report",
    audience: "Strategy & analysts",
    description: "The full evidence-backed intelligence picture with all findings.",
  },
  opportunity: {
    name: "Opportunity Report",
    audience: "Operators",
    description: "Prioritized opportunities and the actions they imply.",
  },
};

function conf(i: GraphInsight): string {
  return `${Math.round((i.trust?.confidence ?? 0) * 100)}% confidence`;
}

export function buildMarkdown(kind: ReportKind, orgName: string, dash: DashboardView): string {
  const meta = REPORT_META[kind];
  const date = new Date().toLocaleDateString(undefined, {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  const lines: string[] = [];
  lines.push(`# ${orgName} — ${meta.name}`);
  lines.push(`*Prepared for ${meta.audience} · ${date}*`);
  lines.push("");

  // Snapshot metrics
  lines.push("## At a glance");
  lines.push(`- Verified findings: ${dash.counts.validated}`);
  lines.push(`- Recommendations: ${dash.counts.recommendations}`);
  lines.push(`- Conflicting intelligence: ${dash.counts.disputes_open}`);
  lines.push(`- Investigations run: ${dash.counts.runs}`);
  lines.push("");

  const recs = dash.recommendations ?? [];
  const findings = dash.validated_insights ?? [];

  if (kind === "executive" || kind === "board") {
    lines.push("## Key recommendations");
    if (recs.length === 0) lines.push("_No recommendations yet._");
    recs.slice(0, kind === "board" ? 3 : 6).forEach((r) => {
      lines.push(`- **${r.title}** — ${conf(r)}`);
      if (r.body && kind === "executive") lines.push(`  - ${r.body}`);
    });
    lines.push("");
    lines.push("## What we verified");
    if (findings.length === 0) lines.push("_No verified findings yet._");
    findings.slice(0, kind === "board" ? 4 : 8).forEach((f) => {
      lines.push(`- ${f.title} (${conf(f)})`);
    });
    lines.push("");
  }

  if (kind === "research") {
    lines.push("## Verified findings");
    if (findings.length === 0) lines.push("_No verified findings yet._");
    findings.forEach((f) => {
      lines.push(`### ${f.title}`);
      if (f.body) lines.push(f.body);
      lines.push(`*${conf(f)} · ${f.claim_ids.length} supporting finding(s)*`);
      lines.push("");
    });
    lines.push("## Recommendations");
    recs.forEach((r) => {
      lines.push(`- **${r.title}** — ${conf(r)}`);
    });
    lines.push("");
  }

  if (kind === "opportunity") {
    lines.push("## Prioritized opportunities");
    if (recs.length === 0) lines.push("_No opportunities surfaced yet._");
    recs.forEach((r, i) => {
      lines.push(`### ${i + 1}. ${r.title}`);
      if (r.body) lines.push(r.body);
      lines.push(`*${conf(r)}*`);
      lines.push("");
    });
  }

  // History
  const history = dash.research_history ?? [];
  if (history.length > 0) {
    lines.push("## Investigation history");
    history.slice(0, 8).forEach((run) => {
      const name = run.playbook?.id
        ? run.playbook.id.replace(/_/g, " ").replace(/\b\w/g, (m) => m.toUpperCase())
        : "Analysis";
      lines.push(`- ${name} — ${new Date(run.created_at).toLocaleDateString()} (${run.status})`);
    });
    lines.push("");
  }

  lines.push("---");
  lines.push(
    "_Generated by Sentient Intelligence OS. Every statement is backed by collected sources; figures requiring a data provider are omitted rather than estimated._",
  );
  return lines.join("\n");
}

/** Minimal, self-contained HTML with print-friendly styling. */
export function buildHTML(kind: ReportKind, orgName: string, dash: DashboardView): string {
  const md = buildMarkdown(kind, orgName, dash);
  const body = md
    .split("\n")
    .map((line) => {
      if (line.startsWith("### ")) return `<h3>${esc(line.slice(4))}</h3>`;
      if (line.startsWith("## ")) return `<h2>${esc(line.slice(3))}</h2>`;
      if (line.startsWith("# ")) return `<h1>${esc(line.slice(2))}</h1>`;
      if (line.startsWith("- ")) return `<li>${inline(line.slice(2))}</li>`;
      if (line.startsWith("*") && line.endsWith("*"))
        return `<p class="muted">${esc(line.replace(/\*/g, ""))}</p>`;
      if (line === "---") return "<hr/>";
      if (line.trim() === "") return "";
      return `<p>${inline(line)}</p>`;
    })
    .join("\n")
    .replace(/(<li>[\s\S]*?<\/li>)(?!\s*<li>)/g, "<ul>$1</ul>");

  return `<!doctype html><html><head><meta charset="utf-8"/>
<title>${esc(orgName)} — ${REPORT_META[kind].name}</title>
<style>
  body{font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;max-width:760px;margin:40px auto;padding:0 24px;color:#1a1a1a;line-height:1.55}
  h1{font-size:26px;margin-bottom:4px}h2{font-size:18px;margin-top:28px;border-bottom:1px solid #eee;padding-bottom:6px}
  h3{font-size:15px;margin-top:18px}.muted{color:#777;font-size:13px}
  ul{padding-left:20px}li{margin:4px 0}hr{border:none;border-top:1px solid #eee;margin:28px 0}
  a{color:#7c3aed}
</style></head><body>${body}</body></html>`;
}

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
function inline(s: string): string {
  return esc(s).replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>");
}
